[package]
name = "stroki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strsim = "0.10.0"
serde_json = "1.0.82"
serde = {version = "1.0.138", features = ["derive"] }